# File: mt5_validator/strategy_loader.py

"""
Loads and prepares master strategies from the research pipeline's output.

This module is responsible for reading the Parquet files generated by the
Diamond and Platinum layers to construct a complete and usable list of
strategy definitions for the live validator.
"""

import pandas as pd
import logging
import os
from typing import List, Dict, Any

# Import the paths from the live configuration
from legacy.mt5_validator.live_config import DIAMOND_DATA_PATH

# Set up a logger for this module
logger = logging.getLogger(__name__)


class StrategyLoader:
    """
    A class dedicated to loading strategy definitions from disk.
    """
    REQUIRED_COLUMNS = ['trigger_key', 'market_rule', 'type', 'sl_def', 'sl_bin', 'tp_def', 'tp_bin', 'trade_type']

    def __init__(self, diamond_path: str = DIAMOND_DATA_PATH):
        """
        Initializes the StrategyLoader with paths to the data directories.

        Args:
            diamond_path (str): The file path to the 'diamond_data' directory.
            platinum_path (str): The file path to the 'platinum_data' directory.
        """
        self.diamond_path = diamond_path
        logger.info(f"StrategyLoader initialized. Reading data from: {diamond_path}.")

    def load_master_strategies(self, instrument_name: str) -> List[Dict[str, Any]]:
        """
        Loads all master strategies for a given instrument.

        This function reads the master report from the Diamond layer and merges it
        with the blueprint definitions from the Platinum layer to create a complete
        strategy object.

        Args:
            instrument_name (str): The name of the instrument to load strategies for
                                   (e.g., 'EURUSD60').

        Returns:
            List[Dict[str, Any]]: A list of dictionaries, where each dictionary
                                  represents a fully defined master strategy.
                                  Returns an empty list if files are not found
                                  or no strategies exist.
        """
        master_report_path = os.path.join(self.diamond_path, 'master_reports', f"{instrument_name}.parquet")

        # --- File Existence Checks ---
        if not os.path.exists(master_report_path):
            logger.error(f"Master strategies report not found at: {master_report_path}")
            return []

        logger.info(f"Loading master strategies for {instrument_name}...")
        try:
            # Load the two essential dataframes
            master_strategies_df = pd.read_parquet(master_report_path, columns=self.REQUIRED_COLUMNS)

            # Adding varification step for robustness
            if not all(col in master_strategies_df.columns for col in self.REQUIRED_COLUMNS):
                logger.error("The master_reports file is missing one or more required columns.")
                return []

            if master_strategies_df.empty:
                logger.warning(f"Master report for {instrument_name} is empty. No strategies to load.")
                return []

            strategies_list = master_strategies_df.to_dict('records')
            
            logger.info(f"Successfully loaded {len(strategies_list)} master strategies.")
            return strategies_list

        except Exception as e:
            logger.error(f"An unexpected error occurred while loading strategies for {instrument_name}: {e}", exc_info=True)
            return []


# --- Example Usage (for testing this file directly) ---
# if __name__ == "__main__":
#     logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(name)s - %(message)s')

#     # This assumes you have run the research pipeline for 'EURUSD60'
#     # and the output files exist.
#     TEST_INSTRUMENT = "EURUSD15" 

#     logger.info(f"--- Testing StrategyLoader for instrument: {TEST_INSTRUMENT} ---")
    
#     # 1. Initialize the loader
#     loader = StrategyLoader(diamond_path=DIAMOND_DATA_PATH)
    
#     # 2. Load the strategies
#     master_strategies = loader.load_master_strategies(TEST_INSTRUMENT)

#     # 3. Print the results
#     if master_strategies:
#         print(f"\nFound {len(master_strategies)} master strategies.")
#         print("--- Example of first strategy loaded ---")
        
#         # Pretty print the first strategy dictionary
#         import json
#         print(json.dumps(master_strategies[0], indent=2))
        
#         logger.info("\nSUCCESS: StrategyLoader test completed successfully.")
#     else:
#         logger.warning(f"No master strategies found or an error occurred for {TEST_INSTRUMENT}.")
#         logger.warning("Please ensure you have run the full research pipeline and that output files exist at the configured paths.")
    
#     logger.info("StrategyLoader test finished.")